---
title: "Ledning"
output: html_document
---


### Energin leds bort


#### Frågeställningar

Hur bra är olika material på att leda värme.


#### Materiel

En skål. Hett vatten. En träsked, en metallsked och en plastsked. Kanske något av glas eller valfritt. 
En IR-kamera.
Föremålen som man ska mäta på med IR-kameran ska ha en tejpbit som är svart på det område där mätningen ska ske. Detta på grund av att emissiviteten kan variera kraftigt, speciellt kan metaller ha ett annat värde än t.ex. trä.



#### Experiment

    • Placera skedarna i en skål, låt dem luta mot kanten.

    • Mät temperaturen hos skedarna med hjälp av IR-kameran.

    • Koka vatten i en vattenkokare.

    • Häll vattnet i skålen med skedar.

    • Låt stå en minut eller två.

    • Titta på eller ta foto av uppställningen så temperaturen på de olika föremålen kan bestämmas. Det räcker med att avgöra ordningen mellan dem avseende temperatur, noggrann mätning behövs ej. Du kan också känna på föremålen.



#### Uppföljning

    • Vilken ordning har de testade materialen i fråga om värmeledning?

    • Vilket material ska man använda för att få så låg värmeledning som möjligt?

    • Är glas en bättre eller sämre värmeledare än trä? Vad innebär detta för ett fönster i ett hus? En del hus har metall runt fönstret, vad innebär det för värmeledningen?

    • Se i listan över värmeledningsförmåga för några material. Stämmer de med din mätning?Ibland betecknas värmeledningsförmågan med (lambda).

*Se figur för typiska exempel på temperaturer och variationer. Silversked 41,8 ºC, träkniv  30,2 ºC, metallsked 36,8 ºC och plastsked 26,0 ºC.*




*I denna figur syns problematiken med emissiviteten. För silverkniven, längst till vänster, verkar det som att temperaturen är lägre längre ner mot det heta vattnet och högre temperatur överst på den svarta tejpen. För träkniven, nummer två i raden, har däremot en högre temperatur närmare det heta vattnet.*

*Observera också att kameran ändrar skalan.*

*Bilden nedan visar de fyra föremålen på en bänk. Områden med ’hög temperatur’ på silver och metallskeden är reflektioner från taklampor, inte en högre temperatur.*











