---
title: "Energiexperiment"
output: html_document
---

`r studentpage <- ""`
`r knitr::knit_child("../website/header-knitr.Rmd")`

Detta material är en följd av övningar och är indelat i olika områden. Område väljs från översta nivån av flikar. Övning väljs från nästa nivå av flikar. 

***

# {.tabset .tabset-fade}

## Inomhusklimat {.tabset .tabset-fade}

`r knitr::knit_child('Område-Inomhusklimat/Kropp_Kammare_temp_78.Rmd')`
`r knitr::knit_child('Område-Inomhusklimat/CO2_klassrum_9GN.Rmd')`



## Energikällor {.tabset .tabset-fade}

`r knitr::knit_child('Område-Energikällor/Solceller_7_elever.md')`
`r knitr::knit_child('Område-Energikällor/Generator_7GN.Rmd')`
`r knitr::knit_child('Område-Energikällor/Vindkraftverk_7GN.Rmd')`



## Energiförluster {.tabset .tabset-fade}


`r knitr::knit_child('Område-Energiförluster/Konvektion_7GN.Rmd')`
`r knitr::knit_child('Område-Energiförluster/Ledning_7GN.Rmd')`
`r knitr::knit_child('Område-Energiförluster/Strålning_9.Rmd')`


## Energieffektivisering {.tabset .tabset-fade}

`r knitr::knit_child('Område-Energieffektivisering/Samverkan_7GN.Rmd')`
`r knitr::knit_child('Område-Energieffektivisering/Husmodell_7GN.Rmd')`
