---
title: ""
output: html_document
---



### Eleven i kammaren


#### Frågeställningar

Hur tror du att koldioxidhalten i ett rum påverkas av att det finns:
    • människor i rummet?
    • brinnande stearinljus i rummet?


#### Materiel

Ett klassrum med människor.
Utrustning för mätning av koldioxidhalt. En IC-meter fungerar bra.



BILD Klassrum, stearinljus, växter?


#### Experiment

Experimentet består av några delexperiment som ska jämföras.

Experiment 1: Referensexperiment

    • Kontrollera att utrustningen fungerar.
    • Mät under några dagar, alternativt en typisk dag med elever i klassrummet.
    • Diskutera hur en typisk dag ser ut och varför. Diskutera eventuella variationer eller avvikelser. Vilket värde har ni på andelen koldioxid då rummet är utvädrat? (ppm)

Experiment 2: Kan vi höja koldioxidhalten?

    • Stäng av ventilationen och täta eventuella större hål i rummet: tröskel, ventilationsgaller o.s.v.
    • Alla utför någon fysisk ansträngning: armhävningar, hoppa...

Experiment 3: Förbränning

    • Låt en del av lektionen pågå och observera om mätningarna ser normala ut.
    • När en del av lektionen pågått så tänd stearinljus eller fotogenlyktor. Observerar ändringen i koldioxidhalt.


Experimenten kan varieras mycket. Fundera om det finns något mer ni kan experimentera med i just er situation på er skola?

Man kan göra mindre experiment i mindre rum, exempelvis grupprum. 

Olika grupper kan göra olika experiment och sedan redovisa och diskutera.



#### Uppföljning

    • Varifrån (vilka processer) kommer koldioxiden i klassrummet då endast människor är i rummet? ppm koldioxid per minut?

    • Varifrån (vilka processer) kommer koldioxiden i klassrummet då endast ett brinnande ljus är i rummet? ppm koldioxid per minut?

    • Vad producerar mest koldioxid per minut, du eller det brinnande ljus ni använde?




#### Information

Normal koldioxidhalt, över marina ytor, var februari 2019 enligt NOAA och Global Greenhouse Gas Reference Network 411 ppm. Ett år tidigare var den 408 ppm. (NOAA: National Oceanic and Atmospheric Administration, USA) Förindustriellt värde är något under 300 ppm, uppgifter varierar mellan 260 och 290 ppm. Över längre tid så fluktuerar värdena mellan 200 och 300 ppm över någotsånär cykliska perioder på 100 000 år de senaste 800 000 åren.

Koldioxidhalten anges som parts per million (miljondelar) ppm. Andelen beräknas som antalet koldioxidmolekyler dividerat med totala antalet molekyler (även koldioxid) i luften, dock ej vattenmolekyler (torr luft). 0,000400 = 400 ppm.



Kopierat och inspirerat av http://www.carboeurope.org/education/indoorhands.php

