---
title: "Untitled"
output: html_document
---

### Generator


#### Frågeställningar

Hur mycket energi kan man få från en elektrisk generator?


#### Materiel

En enkel handdriven generator. Något att mäta spänning och ström med. En stor och en liten resistor, t.ex. 1 Megaohm och 10 Ohm.

*Värdena är inte så noga. Undvik dock  att kortsluta generatorn. I stället för  1 Megaohm kan man använda endast voltmetern som har stort inre motstånd. Har inte varit med om att något går i sönder vid kortslutning över generatorns poler men...*

För att kunna hålla konstant varvtal kan man använda en metronom. Metronomer finns som applikation för mobiltelefoner. Apparna ’Physcis Toolbox Sensor Suite’ och ’Phyphox’ kan också användas.

*Använd gärna ’Physics Toolbox Sensor Suite’ från Vieyra Software. Den använder mobiltelefonens närhetssensor (Proximeter) och man väljer ’pendulum mode’. Låt veven passera sensorn så räknar den tiden mellan passager. Programmet phyphox är också bra och fungerar på ett liknande sätt. Båda är gratis.*



#### Experiment

    • Veva generatorn runt med olika varvtal (rpm) och undersök vilken effekt som erhålls.

    • Variera resistansen från stor (ingen belastning, väldigt liten effekt) till liten (stor belastning, relativt större effekt). Vilken effekt erhålls?







#### Uppföljning

    • Hur känns det att veva vid stor (liten resistans) respektive liten (stor resistans) belastning? Varför är det så? *Trögare vid stor belastning.*

    • Måste en generator rotera fort, varv per minut, för att ge mycket elektrisk energi? *Nej. Ett lugnt vevande med stor belastning kan ge högre effekt (mer energi) än ett snabbt vevande med liten belastning. Praktiskt brukar man diskutera vridmoment.*

    • Vilka faktorer bestämmer hur mycket energi man kan få ut ur generatorn? *Antal varv per minut och vridmoment.*

    • Energi kan varken skapas eller förintas. Varifrån kommer den elektriska energin som generatorn levererar? *Från din egen rörelse.*

    • I ett vindkraftverk driver vinden generatorn. Måste ett vindkraftverk snurra fort för att ge mycket elektrisk energi? *Nej.*

    • Vad driver generatorn i ett kärnkraftverk? *T.ex. ånga som passerar en turbin kopplad till en generator. Ångan skapas av upphettning av t.ex. vatten. Finns många konstruktioner men det viktigaste är att det ändå påminner om vattenkraftverk och vindkraftverk.*



*Vid ett lugnt men inte långsamt vevande, 1 Megaohm, erhölls 6 V och 6 mikroampere, d.v.s. 36 mikrowatt. Vid 1 Ohm erhölls 0,7 V och 0,4 mA vilket är cirka 0,3 mW.*