---
title: "Solceller"
output: html_document
---


### Solceller




#### Frågeställning

Vilka faktorer styr effekten som kan erhållas från en solcell?


#### Material

En solcell större än 1 kvadratdecimeter.
Ställning som kan hålla solcellen fast i olika vinklar. Enklast om solcellen kan roteras kring en axel.
Voltmeter, amperemeter eller wattmeter.
Tjockt svart papper. *Helt ogenomskinligt.*
En liten tavla att redogöra för resultat på.

*Alega har solceller som ger 2 V och 0,5 A. 11,5*8,2 cm. 87,50 kr. De har också plastspeglar 10*8 cm för 30 kr.*




#### Experiment

Rikta en solcell mot solen, använd gärna ett stativ eller hållare.

    1. Mät spänning och ström från solcellen, eller effekt. Ändra solcellens vinkel i förhållande till solen; vad blir det för effekt beroende på vinkel? Konstruera en graf som illustration. Resultatet betyder mycket för hur solceller kan användas.


    2. Använd ett tjockt svart papper för att täcka solcellen i olika omfattning. Börja med att täcka en liten andel (ange i procent) och täck mer och mer. Hur beror effekten på hur stor andel som är täckt? Rita en graf för att illustrera. Resultatet betyder mycket för hur solceller ska skötas.




    3. Även om solcellen är direkt riktad mot solen så blir effekten från solen mindre ju lägre solen står: Varför är det så? Jordens atmosfär är överdriven i bilden.


#### Uppföljning

    • Vilka faktorer är viktiga vid användning av solceller för att få största möjliga effekt?
*Mängden ljus, vinkeln mot solen, mängden absorption i atmosfären. Att solcellens yta är ren. Jämn belysning.*

    • Varför ska en solcell helst se svart ut? *Att den ser svart ut innebär att den absorberat allt ljus(i det synliga området).*

    • Hur kan man få ännu mer solljus på solcellen utan att göra själva solcellen större? *Genom att reflektera solljus från omgivningen. Dock finns det ett maximum så effektivast är det vid låg belysning. Även om man reflekterar ljus till solcellen så är det viktigt att den blir jämnt belyst, svagaste flödet bestämmer strömmen.*

    • Angående första experimentet med solcell. Var på Jorden är det bäst? Hur högt stiger solen som högst under vintern i Sverige? Vilken årstid är det i Sverige på bilden? Rita läget för Jorden ett halvår senare. Vad innebär norra och södra vändkretsarna för solceller; de ligger cirka 23,5 grader norr respektive söder om ekvatorn?
*I Sverige är det sommar, på södra halvklotet vinter. Solen stiger vid Malmös Latitud ca 10 grader över horisonten. Se även https://www.smhi.se/kunskapsbanken/meteorologi/vad-ar-ett-solbanediagram-1.31981 *

