---
title: "Husmodell"
output: html_document
---


### Varmt i huset


#### Frågeställning

Vilket hus kräver minst energi för att upphettas?


#### Materiel

Några modeller av hus. Energibussen har kuber tillverkade av olika material. De upphettas med hjälp av en glödlampa och temperaturen mäts med en digital termometer kopplad till mätprogram. Linjal för bestämning av husens begränsningsarea.


#### Experiment

    • Koppla in termometrar i de hus du vill mäta i.

    • Kontrollera att termometrarna visar samma temperatur, så utgångsläget är ungefär lika.

    • Ställ era hypoteser om vilket hus som kommer att upphettas snabbast. Varför tror ni det?

    • Tänd glödlamporna i alla husen samtidigt.

    • Anteckna temperaturändringarna.

    • Låt temperaturerna stiga en stund.

    • Under tiden temperaturen stiger: Ställ era hypoteser om vilket hus som kommer att svalna snabbast.

    • Uppskatta de olika husens jämvikts/maximala temperaturer.

    • Stäng av alla glödlampor samtidigt och låt husen svalna.

    • Vilket hus svalnar snabbast? Hur bestämmer man det?

    • Om du är bekant med formeln, som gäller vid jämvikt, så använd den för att beräkna de olika materialens U-värde. P är lampans effekt. A är kubens begränsningsarea.  är skillnaden mellan kubens jämviktstemperatur/max och omgivningens temperatur.

    • Variationer och hypoteser:

        ◦ Om en fläkt blåser på husen vad händer då? Vad simulerar detta?
        ◦ Om det finns en stor sten eller en bägare med vatten i huset vad händer då?
        ◦ …
